import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import fs from 'fs';
import matter from 'gray-matter';

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Markdown Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen overflow-x-scroll">
        <div className="max-w-4xl mx-auto px-4 md:px-12">
          <div className="flex flex-col md:flex-row items-center justify-between my-8 md:my-12">
            <h1 className="text-3xl font-bold uppercase tracking-[8px] text-left"> 
            markdown <span className="text-gray-400">blog</span>. 
            </h1>
            <h2 className=" text-gray-400 text-lg mt-4 md:mt-0">
              A statically generated blog using 
              <span className="text-gray-600"> Next.js</span>, 
              <span className="text-gray-600"> Markdown</span>, 
              and 
              <span className="text-gray-600"> dynamic routing</span>.
            </h2>
          </div>
          <div className="py-2">
            <Image 
              src="https://images.unsplash.com/photo-1608447714925-599deeb5a682"
              width="1200"
              height="0"
              alt="hero image"
              className=""
            />
          </div>
          <div className="mt-8 md:text-xl uppercase font-thin tracking-[10px]">
            blog content
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 blog-grid mb-16 mt-4">
            {posts.map(post => {
              const {slug, frontmatter} = post
              const {title, author, category, date, tags, bannerImage} = frontmatter

              return <div className="max-w-sm overflow-hidden group" key={title}>
                <article className="border">
                  <Link href={`/blog/${slug}`}>
                    <Image 
                      src={bannerImage} 
                      width="1000"
                      height="0"
                      alt="blog picture"
                      className="w-full group-hover:opacity-70 transition duration-300" 
                    />
                    <div className="px-6 py-4">
                      <div className="font-bold text-lg h-16">{title}</div>
                    </div>
                    <div className="px-6 pt-4 pb-2 flex justify-center">
                      <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{tags[0]}</span>
                      <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{tags[1]}</span>
                      <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{tags[2]}</span>
                    </div>
                  </Link>
                </article>
              </div>
            })} 
          </div>
        </div>
    </main>
    </>
  )
}

export async function getStaticProps(){
  const files = fs.readdirSync('./src/pages/posts');

  const posts = files.map((fileName) => {
      const slug = fileName.replace('.md', '');
      const readFile = fs.readFileSync(`./src/pages/posts/${fileName}`, 'utf-8');
      const { data: frontmatter } = matter(readFile);

      return {
        slug,
        frontmatter,
      };
  });

  return {
      props: {
        posts,
      },
  };
}


